version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./compose/api/Dockerfile
    ports:
      - "8000:8000"
    env_file: 
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=application
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./compose/api/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data: